### PR TITLE
Bump Chisel 3.4 | RC Bump

### PR DESCRIPTION
**Pull request by abejgonzalez**
Related PR: https://github.com/ucb-bar/chipyard/pull/719

Bump for RC Nov. / Chisel 3.4 / FIRRTL 1.4
- Change `toBool` to `asBool`
- Change `TLBConfig` to take sets and ways

### CODE REVIEW

**Comment by abejgonzalez** [comment]
Any opposition to simplifying the `build.sbt` a bit?

**Comment by hngenc** [comment]
These changes all lgtm. (I don't know enough about build.sbt to comment on those changes though).

Abe, can you apply these changes on the `dev` branch, instead of on `master`?

**Comment by abejgonzalez** [comment]
> These changes all lgtm. (I don't know enough about build.sbt to comment on those changes though).

The `build.sbt` stuff is mainly just removing some extra stuff to make the file a bit cleaner. Additionally, I specify all dependencies explicitly just in case Gemmini wants to be cloned independently of Chipyard in the future (though I don't recommend this).

> Abe, can you apply these changes on the `dev` branch, instead of on `master`?

Done.

**Comment by hngenc** [comment]
CircleCI is giving this error:

```
[error] (mdf / update) sbt.librarymanagement.ResolveException: Error downloading org.scalamacros:paradise_2.12.12:2.1.0
```

Were you able to build the simulator on your own machine? Maybe CircleCI just needs to be updated?

**Comment by abejgonzalez** [comment]
> CircleCI is giving this error:
> 
> ```
> [error] (mdf / update) sbt.librarymanagement.ResolveException: Error downloading org.scalamacros:paradise_2.12.12:2.1.0
> ```
> 
> Were you able to build the simulator on your own machine? Maybe CircleCI just needs to be updated?

This is a CY issue: https://github.com/ucb-bar/chipyard/pull/719#discussion_r541240212. Im waiting a bit for Tim to respond... if not Ill bump everything (I have a couple of barstools changes that need to go in).

**Review by hngenc — APPROVED** [review]
Lgtm, thanks, Abe!

**Pull request merged**
